spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easybuy?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: seckill
  main:
    web-application-type: servlet
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#mybatis:
#  mapper-locations: mapper/*mapper.xml